### ISSUE TITLE
Use with direnv causes 're-eval' every time

### ISSUE THREAD

**Issue by otavio** [almini/nix-zephyr-arm-dev#1]
I use `direnv` for development but the manifest use causes the environment to reload every time.

```console
warning: updating lock file '.../flake.lock':
• Updated input 'manifest':
    'path:/nix/store/g7j3cbfvk8928pgd1dn3cik53i6gm3p8-source/west.yml?lastModified=1&narHash=sha256-3jFZa1eP5xyv+20%2fwXJYRKsxpsmjI28jjMbVr8inny8=' (1970-01-01)
  → 'path:/nix/store/32w72w0xhg2rs3z6ppl7p4hgyxxcx9ri-source/west.yml?lastModified=1&narHash=sha256-3jFZa1eP5xyv+20%2fwXJYRKsxpsmjI28jjMbVr8inny8=' (1970-01-01)
```

**Comment by almini** [comment]
I have also noticed that. You can just remove the manifest from your flake inputs. 
It is only to check if the zephyr version from the manifest is the same as the one in the flake.
I have the feeling it wasn't a good idea anyway and maybe I will also remove it.
